# Generated by Django 4.2.7 on 2023-11-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon_main', '0002_property_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
