# Generated by Django 4.2.7 on 2023-11-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon_main', '0003_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
