# Generated by Django 4.2.7 on 2023-11-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon_main', '0006_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
