# Generated by Django 4.2.7 on 2023-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon_main', '0008_requestviewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestviewing',
            name='is_viewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
