# Generated by Django 4.2.7 on 2023-11-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon_main', '0009_requestviewing_is_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestviewing',
            old_name='user',
            new_name='customer',
        ),
    ]
