# Generated by Django 4.2.7 on 2023-11-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon_main', '0010_rename_user_requestviewing_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='requestviewing',
            options={'verbose_name': 'Booked Viewing', 'verbose_name_plural': 'Booked Viewings'},
        ),
    ]
